### ISSUE TITLE
Error testing with the default test scripts

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-archetype-testng#1]
Test tns:Main type Mandatory default result Passed (s0011)

Assertion: The test subject satisfies all applicable constraints.

Form d1e46_1:
   level=1
   uri=http://www.w3schools.com/xml/note.xml

After creating the archetype, installing the test and running it, the following errors occurred

Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function java.lang.Exception: Fatal Error: XPath syntax error at char 19 on line 47 in {tng:new($outputDir)}:
    Cannot find a matching 1-argument function named {java:org.opengis.cite.waterml20.TestNGController}new(); SystemID: file:/Users/lbermudez/Documents/Dropbox/software/te_build/catalina_base/TE_BASE/work/_Users_lbermudez_Documents_Dropbox_software_te_build_catalina_base_TE_BASE_scripts_waterml20_1.0_ctl_/waterml20-suite/tns$run-ets-waterml20.fn; Line#: 47; Column#: -1
Fatal Error: XPath syntax error at char 40 on line 50 in {...Run($controller, $testRunAr...}:
    Cannot find a matching 2-argument function named {java:org.opengis.cite.waterml20.TestNGController}doTestRun(); SystemID: file:/Users/lbermudez/Documents/Dropbox/software/te_build/catalina_base/TE_BASE/work/_Users_lbermudez_Documents_Dropbox_software_te_build_catalina_base_TE_BASE_scripts_waterml20_1.0_ctl_/waterml20-suite/tns$run-ets-waterml20.fn; Line#: 50; Column#: -1
Failed to compile stylesheet. 2 errors detected.
Result: Failed

**Comment by rjmartell** [comment]
I have not been able to reproduce this stylesheet compilation error with the latest ETS archetype. I invoked the archetype in a local repository like so:

```
mvn archetype:generate -DarchetypeCatalog=local -Dets-code=abc10
```

The resulting test suite built successfully. The suite was then run in TE 4.4 via the CTL wrapper; the test run completed with the expected errors:

```
Form d1e46_1:
   level=1
   uri=http://www.w3schools.com/xml/note.xml

Message d1e187_1:
   Test suite: abc10-0.1-SNAPSHOT
======== Test groups ========
Conformance Level 1
    Passed: 1 | Failed: 2 | Skipped: 0
Conformance Level 2
    Passed: 1 | Failed: 1 | Skipped: 0
```
