### ISSUE TITLE
Update archetype

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-archetype-testng#9]

**Comment by lgoltz** [comment]
Branch: https://github.com/opengeospatial/ets-archetype-testng/tree/update-9

 * Added wiki page https://github.com/opengeospatial/cite/wiki/Developer-Guidelines with Eclipse formatter. Referenced page on https://github.com/opengeospatial/cite/wiki and removed formatter from ETS archetype: https://github.com/opengeospatial/ets-archetype-testng/commit/85293d2c1164818ff9badfa7995b21384cab1962
 * Added Docker and Jenkinsfiles, updated versions: https://github.com/opengeospatial/ets-archetype-testng/commit/2eb21e6ed9d458b84a01b00ac22b9954c461b00f
 * removed jmx file: https://github.com/opengeospatial/ets-archetype-testng/commit/ee9647843b5b9becaab8755f1bd965078efec761
 * Markdown to Asciidoc: https://github.com/opengeospatial/ets-archetype-testng/commit/fc11af95c15635d631f788c41211dbb1e45e720b
 * Added new property to set the short tile (e.g. WFS 3.0): https://github.com/opengeospatial/ets-archetype-testng/commit/e94e0367115b97d82161f3e7934c372132f600a5 

The following command can be used to create a proper (naming!) ets: 
```
mvn archetype:generate -B \
         -DarchetypeGroupId=org.opengis.cite \
          -DarchetypeArtifactId=ets-archetype-testng \
          -DarchetypeVersion=2.7-SNAPSHOT \
          -Dets-code=test42 \
          -Dets-title='Web Test Service (WTS)' \
          -Dets-title-short='WTS 1.0' \
          -DartifactId=ets-test42 \
          -Dpackage=org.opengis.cite.test42
```
The documentation at https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG-Part-1 should be updated.

**Comment by dstenger** [comment]
Documentation was updated https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG-Part-1/_compare/a53d6612ce5ae9ab4365586cd984a06e1c95004a...94bfdb915ce4a5b9e5a92852aca7e4624fcac45d
and hint was added to release issue: https://github.com/opengeospatial/te-releases/issues/243#issuecomment-520383949
